services:
  - type: web
    name: arnav-weather-web
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENWEATHER_API_KEY
        sync: false
