'use strict';
(() => {
  const KEY='arnav-weather-favorites'; const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}; const set=x=>localStorage.setItem(KEY,JSON.stringify(x.slice(0,12)));
  function isFavorite(loc){return get().some(x=>Math.abs(x.lat-loc.lat)<.01&&Math.abs(x.lon-loc.lon)<.01)}
  function toggle(loc){let rows=get();const i=rows.findIndex(x=>Math.abs(x.lat-loc.lat)<.01&&Math.abs(x.lon-loc.lon)<.01);if(i>=0){rows.splice(i,1);set(rows);window.awApp?.toast('Removed from favorites');}else{rows.unshift({name:loc.name,state:loc.state,country:loc.country,lat:loc.lat,lon:loc.lon,updated:Date.now()});set(rows);window.awApp?.toast('Added to favorites','success');}syncButton(loc);renderPage();}
  function syncButton(loc){const b=document.getElementById('aw-fav-btn');if(!b||!loc)return;const on=isFavorite(loc);b.classList.toggle('is-active',on);b.innerHTML=`<i class="${on?'fas':'far'} fa-heart"></i>`;b.setAttribute('aria-label',on?'Remove from favorites':'Add to favorites');}
  async function renderPage(){const grid=document.getElementById('aw-favorites-grid'),empty=document.getElementById('aw-favorites-empty');if(!grid)return;const rows=get();grid.innerHTML='';empty.style.display=rows.length?'none':'block';for(const row of rows){const card=document.createElement('article');card.className='aw-favorite-card';card.innerHTML=`<button class="aw-favorite-card__remove" aria-label="Remove ${row.name}"><i class="fas fa-times"></i></button><div style="font-weight:700">${row.name}</div><div style="font-size:.75rem;color:var(--text-muted)">${[row.state,row.country].filter(Boolean).join(', ')}</div><div class="aw-favorite-card__temp">--°</div><div class="aw-favorite-card__condition">Tap to load weather</div>`;card.addEventListener('click',e=>{if(e.target.closest('button'))return;window.awApp?.loadCoords(row.lat,row.lon,row).then(()=>window.awRouter?.navigate('dashboard'));});card.querySelector('button').addEventListener('click',()=>{set(get().filter(x=>x.lat!==row.lat||x.lon!==row.lon));renderPage();syncButton(window.awApp?.data?.location);});grid.append(card);try{const d=await awApi.bundleByCoords(row.lat,row.lon,row);card.querySelector('.aw-favorite-card__temp').textContent=window.awApp?.temp(d.current.temp)??`${d.current.temp}°`;card.querySelector('.aw-favorite-card__condition').textContent=d.current.condition;}catch{card.querySelector('.aw-favorite-card__condition').textContent='Weather unavailable';}}
  }
  document.addEventListener('DOMContentLoaded',()=>document.getElementById('aw-fav-btn')?.addEventListener('click',()=>{if(window.awApp?.data?.location)toggle(window.awApp.data.location)}));
  window.awFavorites={get,toggle,isFavorite,syncButton,renderPage};
})();
