'use strict';
(() => {
  class ArnavWeatherApp {
    constructor(){this.data=null;this.demoMode=false;this.refreshTimer=null;this.clockTimer=null;}
    get settings(){return window.awSettings?.state||{units:'celsius',windUnit:'kmh',pressureUnit:'hpa',distUnit:'km',timeFormat:'12h',defaultCity:'Delhi',useLocation:false};}
    temp(c){return `${this.settings.units==='fahrenheit'?AWWeather.cToF(c):Math.round(c)}°${this.settings.units==='fahrenheit'?'F':'C'}`;}
    wind(k){return this.settings.windUnit==='mph'?`${AWWeather.kmhToMph(k)} mph`:`${Math.round(k)} km/h`;}
    pressure(h){return this.settings.pressureUnit==='inhg'?`${AWWeather.hpaToInhg(h)} inHg`:`${Math.round(h)} hPa`;}
    distance(k){return this.settings.distUnit==='miles'?`${AWWeather.kmToMiles(k)} mi`:`${k} km`;}
    toast(message,type='info',timeout=3300){const box=document.getElementById('aw-toast-container');if(!box)return;const el=document.createElement('div');el.className=`aw-toast aw-toast--${type}`;const icon=type==='success'?'circle-check':type==='error'?'triangle-exclamation':'circle-info';el.innerHTML=`<i class="fas fa-${icon}" style="color:var(--accent-${type==='info'?'primary':type})"></i><div>${message}</div>`;box.append(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateX(15px)';setTimeout(()=>el.remove(),250)},timeout);}
    setLoader(message){const l=document.getElementById('aw-app-loader'),m=document.getElementById('aw-loader-message');if(m)m.textContent=message;if(l)l.classList.remove('is-hidden');}
    hideLoader(){document.getElementById('aw-app-loader')?.classList.add('is-hidden');}
    async loadCity(city,{initial=false}={}){city=String(city||'').trim();if(!city)return;this.setLoader(`Loading weather for ${city}…`);try{this.data=await awApi.bundleByCity(city);this.demoMode=false;this.saveRecent(this.data.location);this.renderAll();if(!initial)this.toast(`Weather updated for ${this.data.location.name}`,'success');}catch(e){if(e.code==='API_KEY_REQUIRED'||e.status===503){this.data=AWWeather.demo();this.demoMode=true;this.renderAll();this.toast('OpenWeather key is missing. Showing polished demo data. Add OPENWEATHER_API_KEY to .env.','error',6500);}else{this.toast(e.message||`Could not load ${city}`,'error',5000);if(!this.data){this.data=AWWeather.demo();this.demoMode=true;this.renderAll();}}}finally{this.hideLoader();}}
    async loadCoords(lat,lon,hint={},{initial=false}={}){this.setLoader('Loading weather for your location…');try{this.data=await awApi.bundleByCoords(lat,lon,hint);this.demoMode=false;this.saveRecent(this.data.location);this.renderAll();if(!initial)this.toast('Location weather updated','success');}catch(e){if(e.code==='API_KEY_REQUIRED'||e.status===503){this.data=AWWeather.demo();this.demoMode=true;this.renderAll();this.toast('API key missing. Showing demo data.','error',5500);}else{this.toast(e.message||'Unable to load this location','error');}}finally{this.hideLoader();}}
    useLocation({initial=false}={}){return new Promise(resolve=>{if(!navigator.geolocation){this.toast('Geolocation is not supported by this browser.','error');resolve(false);return;}const buttons=[document.getElementById('aw-header-location-btn'),document.getElementById('aw-search-location-btn')].filter(Boolean);buttons.forEach(b=>{b.disabled=true;b.innerHTML='<i class="fas fa-spinner fa-spin"></i>'});navigator.geolocation.getCurrentPosition(async pos=>{await this.loadCoords(pos.coords.latitude,pos.coords.longitude,{name:'Current Location'},{initial});buttons.forEach(b=>{b.disabled=false;b.innerHTML='<i class="fas fa-location-crosshairs"></i>'});resolve(true)},err=>{const msg=err.code===1?'Location permission was denied. You can search for a city instead.':err.code===2?'Your location is currently unavailable.':'Location request timed out.';this.toast(msg,'error',5000);buttons.forEach(b=>{b.disabled=false;b.innerHTML='<i class="fas fa-location-crosshairs"></i>'});resolve(false)},{enableHighAccuracy:true,timeout:10000,maximumAge:300000});});}
    saveRecent(loc){try{let rows=JSON.parse(localStorage.getItem('arnav-weather-recent')||'[]');rows=rows.filter(x=>x.name!==loc.name||x.country!==loc.country);rows.unshift({name:loc.name,state:loc.state,country:loc.country,lat:loc.lat,lon:loc.lon});localStorage.setItem('arnav-weather-recent',JSON.stringify(rows.slice(0,8)));}catch{}}
    renderAll(){if(!this.data)return;this.renderHero();this.renderHourly();this.renderDaily();this.renderInsights();window.awFavorites?.syncButton(this.data.location);window.awAnimations?.update(this.data.current.id);if(window.awRouter?.current==='airquality')window.awAirQuality?.render(this.data.location.lat,this.data.location.lon);if(window.awRouter?.current==='favorites')window.awFavorites?.renderPage();}
    renderHero(){const d=this.data,cur=d.current,loc=d.location,s=this.settings,offset=loc.offset;const set=(id,text)=>{const el=document.getElementById(id);if(el)el.textContent=text};set('aw-hero-city',loc.name);set('aw-hero-country',[loc.state,loc.country].filter(Boolean).join(', ')+(this.demoMode?' · Demo':''));set('aw-hero-date',AWWeather.formatDate(cur.epoch,offset));set('aw-hero-time',AWWeather.formatTime(cur.epoch,offset,s.timeFormat));set('aw-hero-temp',s.units==='fahrenheit'?AWWeather.cToF(cur.temp):cur.temp);set('aw-hero-temp-unit',s.units==='fahrenheit'?'°F':'°C');set('aw-hero-condition',cur.condition);set('aw-hero-feels',`Feels like ${this.temp(cur.feels)}`);set('aw-metric-humidity',`${cur.humidity}%`);set('aw-metric-wind',this.wind(cur.windKmh));set('aw-metric-pressure',this.pressure(cur.pressure));set('aw-metric-vis',this.distance(cur.visibilityKm));set('aw-metric-uv',`${cur.uv} est.`);set('aw-metric-rain',`${d.hourly[0]?.pop||0}%`);set('aw-sunrise',AWWeather.formatTime(cur.sunrise,offset,s.timeFormat));set('aw-sunset',AWWeather.formatTime(cur.sunset,offset,s.timeFormat));const icon=document.getElementById('aw-hero-icon');if(icon)icon.innerHTML=AWWeather.iconMarkup(cur.id,'hero');const hero=document.querySelector('.aw-weather-hero');if(hero)hero.dataset.condition=AWWeather.iconClass(cur.id);}
    hourlyCard(h,i){return `<article class="aw-hour-card ${i===0?'is-current':''}" role="listitem"><div class="aw-hour-card__time">${i===0?'Now':AWWeather.formatTime(h.epoch,this.data.location.offset,this.settings.timeFormat)}</div><div class="aw-hour-card__icon">${AWWeather.iconMarkup(h.id,'sm')}</div><div class="aw-hour-card__temp">${this.temp(h.temp)}</div><div class="aw-hour-card__rain"><i class="fas fa-droplet"></i> ${h.pop}%</div></article>`;}
    renderHourly(){const rows=this.data.hourly.slice(0,16);const slider=document.getElementById('aw-hourly-slider');if(slider)slider.innerHTML=rows.map((h,i)=>this.hourlyCard(h,i)).join('');const list=document.getElementById('aw-hourly-list');if(list)list.innerHTML=rows.map((h,i)=>`<article class="aw-hour-row" role="listitem"><strong>${i===0?'Now':AWWeather.formatTime(h.epoch,this.data.location.offset,this.settings.timeFormat)}</strong><div class="aw-hour-row__icon">${AWWeather.iconMarkup(h.id,'xs')}</div><div><strong class="aw-hour-row__condition">${h.condition}</strong><div style="font-size:.75rem;color:var(--text-muted)">${this.temp(h.temp)} · feels ${this.temp(h.feels)}</div></div><div class="aw-hour-row__metric"><i class="fas fa-droplet"></i> ${h.pop}%</div><div class="aw-hour-row__metric"><i class="fas fa-water"></i> ${h.humidity}%</div><div class="aw-hour-row__metric"><i class="fas fa-wind"></i> ${this.wind(h.windKmh)}</div><div class="aw-hour-row__metric"><i class="fas fa-gauge"></i> ${this.pressure(h.pressure)}</div></article>`).join('');this.renderChart(rows.slice(0,10));this.bindSlider();}
    bindSlider(){const slider=document.getElementById('aw-hourly-slider'),left=document.getElementById('aw-hourly-scroll-left'),right=document.getElementById('aw-hourly-scroll-right');if(!slider)return;const update=()=>{left.disabled=slider.scrollLeft<=3;right.disabled=slider.scrollLeft+slider.clientWidth>=slider.scrollWidth-3};left.onclick=()=>slider.scrollBy({left:-380,behavior:'smooth'});right.onclick=()=>slider.scrollBy({left:380,behavior:'smooth'});slider.onscroll=update;slider.onwheel=e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();slider.scrollLeft+=e.deltaY;}},{passive:false};setTimeout(update,0);}
    renderChart(rows){const svg=document.getElementById('aw-temp-chart-svg');if(!svg||!rows.length)return;const w=900,h=220,p=30,temps=rows.map(x=>this.settings.units==='fahrenheit'?AWWeather.cToF(x.temp):x.temp),min=Math.min(...temps)-2,max=Math.max(...temps)+2;const pts=temps.map((t,i)=>[p+i*(w-2*p)/(temps.length-1),h-p-(t-min)*(h-2*p)/(max-min||1)]);const line=pts.map((p,i)=>`${i?'L':'M'}${p[0]},${p[1]}`).join(' '),area=`M${pts[0][0]},${h-p} ${line.replace(/^M/,'L')} L${pts.at(-1)[0]},${h-p} Z`;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=`<defs><linearGradient id="awChartGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="var(--accent-primary)" stop-opacity=".35"/><stop offset="1" stop-color="var(--accent-primary)" stop-opacity="0"/></linearGradient></defs><path class="aw-chart-area" d="${area}"/><path class="aw-chart-line" d="${line}"/>${pts.map((pt,i)=>`<circle class="aw-chart-dot" cx="${pt[0]}" cy="${pt[1]}" r="5"/><text class="aw-chart-label" text-anchor="middle" x="${pt[0]}" y="${pt[1]-12}">${temps[i]}°</text><text class="aw-chart-label" text-anchor="middle" x="${pt[0]}" y="${h-7}">${i===0?'Now':AWWeather.formatTime(rows[i].epoch,this.data.location.offset,this.settings.timeFormat).replace(' ','')}</text>`).join('')}`;}
    dayCard(day,full=false){const date=new Date(`${day.key}T00:00:00Z`);const label=date.toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'}),dateText=date.toLocaleDateString('en-US',{day:'numeric',month:'short',timeZone:'UTC'});return `<article class="aw-day-card" role="listitem" tabindex="0"><div class="aw-day-card__day">${label}</div><div class="aw-day-card__date">${dateText}</div><div class="aw-day-card__icon">${AWWeather.iconMarkup(day.id,'lg')}</div><div class="aw-day-card__temps">${this.temp(day.max)} <span class="aw-day-card__min">/ ${this.temp(day.min)}</span></div><div class="aw-day-card__condition">${day.condition}</div><div class="aw-day-card__rain"><i class="fas fa-droplet"></i> ${day.pop}% rain</div><div class="aw-day-card__extra"><div>Humidity: ${day.humidity}%</div><div>Max wind: ${this.wind(day.windKmh)}</div><div>Precipitation: ${day.precip} mm</div><div>Tap again to collapse</div></div></article>`;}
    renderDaily(){const days=this.data.daily;const preview=document.getElementById('aw-fiveday-preview'),list=document.getElementById('aw-fiveday-list');if(preview)preview.innerHTML=days.map(d=>this.dayCard(d)).join('');if(list)list.innerHTML=days.map(d=>this.dayCard(d,true)).join('');document.querySelectorAll('.aw-day-card').forEach(c=>{const toggle=()=>c.classList.toggle('is-expanded');c.addEventListener('click',toggle);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});}
    renderInsights(){const d=this.data,days=d.daily,avgHum=Math.round(days.reduce((s,x)=>s+x.humidity,0)/(days.length||1)),maxWind=Math.max(...days.map(x=>x.windKmh),0),rain=days.reduce((s,x)=>s+x.precip,0).toFixed(1),uv=d.current.uv;const rows=[['droplet','Average Humidity',`${avgHum}%`],['wind','Maximum Wind',this.wind(maxWind)],['cloud-rain','Forecast Rain',`${rain} mm`],['sun','UV Estimate',`${uv} / 10`]];const box=document.getElementById('aw-insights');if(box)box.innerHTML=rows.map(([icon,label,value])=>`<article class="aw-insight-card" role="listitem"><div class="aw-insight-card__top"><div class="aw-insight-card__icon"><i class="fas fa-${icon}"></i></div></div><div class="aw-insight-card__value">${value}</div><div class="aw-insight-card__label">${label}</div></article>`).join('');}
    scheduleRefresh(){clearInterval(this.refreshTimer);const mins=Number(this.settings.updateInterval||10);this.refreshTimer=setInterval(()=>{if(this.data&&!this.demoMode)this.loadCoords(this.data.location.lat,this.data.location.lon,this.data.location,{initial:true})},mins*60000);}
    async init(){document.getElementById('aw-header-location-btn')?.addEventListener('click',()=>this.useLocation());document.getElementById('aw-unit-toggle')?.addEventListener('click',()=>{const select=document.getElementById('aw-setting-units');if(select){select.value=this.settings.units==='celsius'?'fahrenheit':'celsius';select.dispatchEvent(new Event('change'));}});window.addEventListener('aw:settingschange',()=>{this.renderAll();this.scheduleRefresh()});window.addEventListener('aw:routechange',e=>{if(!this.data)return;if(e.detail.route==='airquality')window.awAirQuality?.render(this.data.location.lat,this.data.location.lon);if(e.detail.route==='favorites')window.awFavorites?.renderPage();});this.clockTimer=setInterval(()=>this.renderHero(),60000);const useLoc=this.settings.useLocation;let loaded=false;if(useLoc)loaded=await this.useLocation({initial:true});if(!loaded)await this.loadCity(this.settings.defaultCity||'Delhi',{initial:true});this.scheduleRefresh();}
  }
  document.addEventListener('DOMContentLoaded',()=>{window.awApp=new ArnavWeatherApp();window.awApp.init().catch(e=>{console.error(e);document.getElementById('aw-global-error')?.classList.remove('aw-hidden');window.awApp.hideLoader();});});
})();
